---

- name: Get jenkins-ci key
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    dest: /tmp/jenkins-ci.key

- apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins.list
  notify: Update repositories cache

- apt_repository:
    repo: ppa:openjdk-r/ppa
  notify: Update repositories cache

- name: Install openjdk-8-jdk
  apt:
    name: openjdk-7-jdk
    state: present
    allow_unauthenticated: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    allow_unauthenticated: yes

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: True

- name: install extera packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_list }}"

- name: Create awscli symlink
  file:
    src: /bin/aws
    dest: /usr/local/bin/aws
    state: link
